set number
set t_Co=256
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()
colorscheme gruvbox
set bg=dark
syntax on
set autoindent
set smartindent
set tabstop=6
set shiftwidth=6
set expandtab
set textwidth=120
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
set nocompatible
set comments=sl:/*,mb:\ *,elx:\ */
